# Generated by Django 5.1.2 on 2024-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_nationality', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('screen_size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10)),
                ('country_of_manufacture', models.CharField(max_length=100)),
            ],
        ),
    ]
